name: laptop_harbor
description: LaptopHarbor — E-Commerce Laptop Shopping App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Google Fonts (Poppins font ke liye)
  google_fonts: ^6.1.0

  # Carousel / Banners ke liye
  carousel_slider: ^4.2.1

  # Star rating ke liye
  flutter_rating_bar: ^4.0.1

  # Local storage ke liye
  shared_preferences: ^2.2.2

  # Network images ke liye
  cached_network_image: ^3.3.1

  # Loading shimmer effect
  shimmer: ^3.0.0

  # State management
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets folder (images ke liye)
  assets:
    - assets/images/
    - assets/icons/
